### ISSUE TITLE
How to setup my own chain?

### ISSUE THREAD

**Issue by Magicloud** [forbole/big-dipper-2.0-cosmos#1131]
Seems like this part of the document has not been updated yet (to follow the latest source).

I have a chain for internal test, basically a fork of one existing cosmos-based chain.

I tried to change things as I did it before in chain.json. I got yarn issue (does not seem related to the chain.json change) and could not build the source.

Then I tried to use existing images from Docker hub and replace some strings. This time I got totally confused and it did not seem to work.

**Comment by teamchong** [comment]
hi @Magicloud 
can you share the error message of your yarn issue?

**Comment by Magicloud** [comment]
@teamchong  Thanks for the reply. My problem with yarn was that, after `yarn install`, there was no Yarn PnP files, hence later steps failed.

Just got it worked. Changed some steps comparing to the Dockerfile here to use `node_modules/`. Seems like fine.
