### ISSUE TITLE
Add docs site with CICD

### ISSUE THREAD

**Issue by kwunyeung** [forbole/big-dipper-2.0-cosmos#143]
Improve documentation with CICD in each PR. Add documentation site at https://docs.bigdipper.live . [Docusaurus](https://docusaurus.io/) is recommended as it is Reach based. 

Examples of doc sites building with Docusaurus are 

* https://wiki.polkadot.network/
* https://docs.solana.com/

**Comment by ryuash** [comment]
Should i make it in this repo or a new repo

**Comment by kwunyeung** [comment]
Make it in the same repo is better as the docs can be updated in each PR in CI.

**Comment by ryuash** [comment]
Does this does include bdjuno + hasura + psql?

**Comment by kwunyeung** [comment]
Yes we need to mention them for the setup but we can point to the corresponding documentations in that section. It depends on how detail we would like to write in that section. The docs can always be improved.
