### ISSUE TITLE
LikeCoin: custom messages

### ISSUE THREAD

**Issue by kwunyeung** [forbole/big-dipper-2.0-cosmos#204]
LikeCoin implement `x/iscn` module and there are 3 custom messages. They can be found at

https://github.com/likecoin/likecoin-chain/blob/fotan-1/x/iscn/types/msgs.go#L18

And these are the protobuf.

https://github.com/likecoin/likecoin-chain/blob/fotan-1/proto/iscn/tx.proto

**Comment by ryuash** [comment]
note: close #215 first
