### ISSUE TITLE
What is the proper values of WS in .env file

### ISSUE THREAD

**Issue by lebrian9889** [forbole/big-dipper-2.0-cosmos#286]
Hello guys,

Follow the configuration guide, I can successfully connect UI to Hasura graphql but failed to use websocket endpoints.

In .env file, I saw this config

```
NEXT_PUBLIC_GRAPHQL_URL=http://localhost:8080/v1/graphql ---> OK

NEXT_PUBLIC_GRAPHQL_WS=ws://localhost:8080  ---> FAILED

NEXT_PUBLIC_URL=http://localhost:3000 ---> OK

NEXT_PUBLIC_WS_CHAIN_URL=ws://localhost:3000 ---> IDK

NEXT_PUBLIC_CHAIN_STATUS= ----> IDK
```

Can you tell me what value do I need to fill in the config file

**Comment by ryuash** [comment]
have you tried:
```
NEXT_PUBLIC_GRAPHQL_WS=ws://localhost:8080/v1/graphql
```

**Comment by ryuash** [comment]
@lebrian9889 
I've update the [docs](https://docs.bigdipper.live/cosmos-based/frontend/setup)

**Comment by lebrian9889** [comment]
thank you, everything works perfectly
