### ISSUE TITLE
terra: setup custom messages

### ISSUE THREAD

**Issue by ryuash** [forbole/big-dipper-2.0-cosmos#347]

**Comment by kanniec826** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Big-Dipper-613717c19c817a00128862f2/issues/forbole/big-dipper-2.0-cosmos/347?planning-poker) with ZenHub @ryuash

**Comment by ryuash** [comment]
Closing as it's been merged with no issues.
