### ISSUE TITLE
emoney: matomo

### ISSUE THREAD

**Issue by ryuash** [forbole/big-dipper-2.0-cosmos#351]

**Comment by kwunyeung** [comment]
url: https://analytics.bigdipper.live/
site Id: 12

**Comment by ryuash** [comment]
Great. Will add this to the new release

**Comment by kwunyeung** [comment]
@ryuash analytics for e-money is still missing.

**Comment by ryuash** [comment]
@kwunyeung  Should be fixed now, can you confirm?

**Comment by kwunyeung** [comment]
It's working now.
