### ISSUE TITLE
[e-Money] Showing standard gas prices

### ISSUE THREAD

**Issue by kwunyeung** [forbole/big-dipper-2.0-cosmos#354]
`e-Money` has a standard `gas-prices` for all transactions. This can be updated via the `x/authority` in `e-Money`. The gas prices can be any stable coins as well as `ungm`. We may show these on the `params` page.

**Comment by kanniec826** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Big-Dipper-613717c19c817a00128862f2/issues/forbole/big-dipper-2.0-cosmos/354?planning-poker) with ZenHub @huichiaotsou

**Comment by kanniec826** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Big-Dipper-613717c19c817a00128862f2/issues/forbole/big-dipper-2.0-cosmos/354?planning-poker) with ZenHub @yayay927

**Comment by ryuash** [comment]
@yayay927 

Below is the raw query data directly from the chain. 

```
{
  "min_gas_prices": [
    {
      "denom": "echf",
      "amount": "0.530000000000000000"
    },
    {
      "denom": "edkk",
      "amount": "3.700000000000000000"
    },
    {
      "denom": "eeur",
      "amount": "0.500000000000000000"
    },
    {
      "denom": "enok",
      "amount": "6.100000000000000000"
    },
    {
      "denom": "esek",
      "amount": "5.500000000000000000"
    },
    {
      "denom": "ungm",
      "amount": "1.000000000000000000"
    }
  ]
}
```

We will want to display this inside the params page [https://emoney.bigdipper.live/params](https://emoney.bigdipper.live/params). See if you can browse around and find the reusable component

The table should look something like:

```
ungm: 1.0
esek: 5.50
enok: 6.10
etc
```
