### ISSUE TITLE
emoney: add liquidityprovider tx

### ISSUE THREAD

**Issue by yayay927** [forbole/big-dipper-2.0-cosmos#355]

**Comment by kanniec826** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Big-Dipper-613717c19c817a00128862f2/issues/forbole/big-dipper-2.0-cosmos/355?planning-poker) with ZenHub @yayay927

**Comment by ryuash** [comment]
Closing as it's been merged with no issues.
