### ISSUE TITLE
Opps! Looks like something went wrong :(

### ISSUE THREAD

**Issue by enginer** [forbole/big-dipper-2.0-cosmos#365]
URL to reproduce:
https://explorer-umee.nodes.guru/accounts/umee1utmuht7zehcrdykvsljj6dafrq6pd88hwlrmg0

**Comment by ryuash** [comment]
Seems their `tokenUnits` in chain_config has been setup incorrectly. Please report this back to the Umee team as Forbole is not the maintainer of this big dipper.
