### ISSUE TITLE
[Base] Latest block columns changing width

### ISSUE THREAD

**Issue by RiccardoM** [forbole/big-dipper-2.0-cosmos#377]
Currently inside the _latest block_ list, the columns keep changing width based on the proposer name length. Maybe it would be better to have the column width fixed instead? 

https://user-images.githubusercontent.com/9119016/134627578-7f293280-8b6a-4753-83db-7ea6c4ac1c9b.mp4

**Comment by ryuash** [comment]
After taking a peek, unless we are okay with hiding part of the proposer's name there's no actual fixes/ optimization for this
