### ISSUE TITLE
Base: Transaction layout on Account Details

### ISSUE THREAD

**Issue by Rooty2020** [forbole/big-dipper-2.0-cosmos#391]
Someone has some feedback about Big Dipper in TG: 

> Can the transaction display go back to the previous version, which is, the transaction amount was displayed upfront? Now I have to click into it one by one to verify the transaction and it is too time consuming.

Current one:
![Screenshot 2021-09-27 at 5.50.57 PM.png](https://images.zenhubusercontent.com/6111e85453613f2c8109c600/4722b4c2-83cf-4635-9bb1-3a2a8508c29f)

UI
![Screenshot 2021-09-27 at 5.52.45 PM.png](https://images.zenhubusercontent.com/6111e85453613f2c8109c600/0feeb5e3-46bf-4a18-8477-025a97a10fd6)

**Comment by ryuash** [comment]
The ui did not work with the layout. It's currently not a top priority, we'll come back to this in the future
