### ISSUE TITLE
[Base] Display desmos profile native address in connections

### ISSUE THREAD

**Issue by ryuash** [forbole/big-dipper-2.0-cosmos#420]
Previously we decided not to include the native desmos profile creator's address to connections but now that desmos profile is appearing on different big dippers it becomes obvious that we should.

![image](https://user-images.githubusercontent.com/42913823/135850540-e6a90519-5a1c-4c87-8d6f-0ccc39965845.png)

Objective:
Display the native address as the first connection with **Network** as `Native`

**Comment by kanniec826** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Big-Dipper-613717c19c817a00128862f2/issues/forbole/big-dipper-2.0-cosmos/420?planning-poker) with ZenHub @yayay927
