### ISSUE TITLE
Error report

### ISSUE THREAD

**Issue by Omertaq** [forbole/big-dipper-2.0-cosmos#471]
I wanted to check my wallet address in excplorer https://explorer.evmos.org/. When I entered my address: *evmos1qs5v8nxf5sn4gp3f7u6zn2ucv3nfe9y4cwqkga* it showed an error and asked to report it to github. Link to the error: https://explorer.evmos.org/accounts/evmos1qs5v8nxf5sn4gp3f7u6zn2ucv3nfe9y4cwqkga

**Comment by ryuash** [comment]
duplicate of #464 
closing.
