### ISSUE TITLE
Base: Display APR (and APY) next to inflation

### ISSUE THREAD

**Issue by RiccardoM** [forbole/big-dipper-2.0-cosmos#483]
Currently BigDipper only displays the inflation of a network, however this measurement is not sufficient to understand how much you are going to earn over your staked assets during a year. To solve this, we could display the APR (Annual Percentage Return) and APY (Annual Percentage Yield). Both of these can be easily computed with the following formulas: 

## APR
<img height="75" src="https://user-images.githubusercontent.com/9119016/139285475-514ae7ae-57f1-4c58-acff-ad57e9ad1b5d.png" />

## APY
<img height="65" src="https://user-images.githubusercontent.com/9119016/139286289-35430d35-e88d-467f-b412-f1d2b1bf78fe.png" />

Where `N` is the number of compounding periods over a year. Considering a daily compounding, this would then be

<img height="65" src="https://user-images.githubusercontent.com/9119016/139286421-9f94d927-d973-4bb4-a125-bbad4542fe31.png" />

## Note
All of the resulting values should be multiplied by `100` to get the percentage values. Some test cases to see if you compute it correctly: 

### APR
Bonded tokens: `43679371`
Supply: `104967613`
Inflation: `46`
**APR**: `110.54%`

### APY
APR: `110.54%`
Compounding periods: `365`
**APY**: `201.54%` 

Originally reported by @angelorc

**Comment by kwunyeung** [comment]
For Big Dipper, I think showing APR would be enough. The APY depends on whether the delegators are withdrawing and delegating every day. The APR actually be affected by the average block time as we have `blocks_per_year: "5339695"` in the `mint` parameters. Translate to block time is around 5.9 seconds. `DSM` is being minted on every block based on this parameter. Mainnet is currently around 5% slower than the expected block time and hence the APR would be 5% less than expected.

**Comment by ryuash** [comment]
So should i follow the formula above to display the APR?

**Comment by kwunyeung** [comment]
@ryuash using the formula and take the block time into account.

**Comment by ryuash** [comment]
@Rooty2020 I need help finding a place on the UI to put the **APR**
