### ISSUE TITLE
base: Filter out validator with top 34% voting power

### ISSUE THREAD

**Issue by kwunyeung** [forbole/big-dipper-2.0-cosmos#506]
Currently there is no way to encourage delegators not to delegate to the top 34% voting power validators. The top 34% validators can collude and start censorship based on BFT. As the current default sorting is not by voting power, we will need an indicator to show delegators not to delegate to them.

This is how Solanabeach.io filter out the top 34%.

![image.png](https://images.zenhubusercontent.com/610d12dcbed147b45e407c24/83eecc10-4ea8-487e-b263-2848c175fe3a)

They are being folded into a group which you can't even see them in the list.

However, if you sort them in other orders, e.g. commission, they will be shown without indication. This is actually dangerous as the validators with high voting power can set a very low commission and rank themselves at top. 

@Rooty2020 @ryuash @MonikaCat do you have any suggestions on this issue?

**Comment by ryuash** [comment]
Need some time to think about this as I would prefer to do it in a way that doesn't try to penalize top validators.

**Comment by ryuash** [comment]
@kwunyeung 
Just a thought but how about I add a new column "hunger" (hunger level) and it has a pop up info explaining about VP and how evenly distributed is better than validators with too much.

Then the enum would be "over eating" "just right" "still hungry" "starving" 

I haven't thought out the actual specs yet but I feel as an explorer we shouldn't try to hide validators or push an objective directly, but we can do it in an educational style while showing everyone

**Comment by kwunyeung** [comment]
@ryuash your idea is similar to the poverty situation. I think there are ways to define how we consider rich and how we consider poor. Found how HK gov define poverty in HK. They have a method to build the stats. https://www.censtatd.gov.hk/en/scode461.html#section8

**Comment by ryuash** [comment]
@kwunyeung  Right..then the first comment will also not work. We should not try to force or change anything at all in this case. Just list out all the data and let the delegator do their own research.

**Comment by kwunyeung** [comment]
@ryuash but 34% is an important number in BFT network. I think it's worth mentioning even if we don't hide those validators.

**Comment by ryuash** [comment]
Okay, that i can work with. Let me add this to the next milestone
