### ISSUE TITLE
Website is crush if use google translater

### ISSUE THREAD

**Issue by catcaster** [forbole/big-dipper-2.0-cosmos#553]
![Снимок экрана 2021-11-23 в 17 13 17](https://user-images.githubusercontent.com/91130813/143050716-34984513-80e4-4305-932c-2ac55493b300.png)

**Comment by ryuash** [comment]
This seems to be a general problem with React and Google translator itself. Please refer to the link i provided
https://github.com/lingui/js-lingui/issues/1079#issuecomment-857702205

**Comment by catcaster** [comment]
Thanks for reply

**Comment by ryuash** [comment]
No problem.
Since this isn't something we can patch directly I will be closing this issue until there is a possible fix.
