### ISSUE TITLE
Still Unable To Get Validator Information To Display

### ISSUE THREAD

**Issue by lightiv** [forbole/big-dipper-2.0-cosmos#594]
I just setup https://gravity-bridge.skynetexplorers.com/ based on  desmos-mainnet-1-v1.8.4 and base-v1.8.4.  I followed the instructions on https://docs.bigdipper.live/cosmos-based/frontend/setup.  On either build it does not display any validator details.

The data is in the database:

![image](https://user-images.githubusercontent.com/36428473/145267741-01b423e5-cc95-46e5-9309-06f302ea7f35.png)

.env:
```
NODE_ENV=production
PORT=3000
NEXT_PUBLIC_CHAIN_STATUS=testnet
NEXT_PUBLIC_GRAPHQL_URL=https://gravity-hasura.skynetexplorers.com/v1/graphql
NEXT_PUBLIC_GRAPHQL_WS=wss://gravity-hasura.skynetexplorers.com/v1/graphql
NEXT_PUBLIC_URL=https://gravity.skynetexplorers.com
NEXT_PUBLIC_WS_CHAIN_URL=wss://gravity-rpc.skynetexplorers.com/websocket
```

The database blocks start 14,970

```
{
  "title": "Gravity Bridge Explorer",
  "network": "gravity-bridge-test4",
  "icon": "https://skynet-images.s3.filebase.com/evmos-logo.svg?sanitize=true",
  "logo": {
    "default": "https://skynet-images.s3.filebase.com/SkyNet-Explorers-Logo.png?sanitize=true"
  },
  "prefix": {
    "consensus": "gravityvalcons",
    "validator": "gravityvaloper",
    "account": "gravity"
  },
  "genesis": {
    "time": "2021-11-28T14:45:49.658958945Z",
    "height": 14970
  },
  "primaryTokenUnit": "ugraviton",
  "tokenUnits": {
    "ugraviton": {
      "display": "graviton",
      "exponent": 6
    }
  },
  "extra": {
    "profile": true
  }
}
```

**Comment by ryuash** [comment]
Hey I just ran your setup on `base-v1.8.4` and `desmos-v1.8.4` and it seems to work fine:

![image](https://user-images.githubusercontent.com/42913823/145315128-c8e054a5-4b5b-452e-a2d9-df82273f4b72.png)

![image](https://user-images.githubusercontent.com/42913823/145315428-b94a1149-4d79-410a-85c2-6c38a0178f2f.png)


Seems like your config file is incorrect. This is the network payload from https://gravity-bridge.skynetexplorers.com/ 

![image](https://user-images.githubusercontent.com/42913823/145315356-c33f3215-b12b-40be-a77e-a2826109838c.png)

**Comment by lightiv** [comment]
Wow, which config file is this because I changed everything to graviton and ugraviton for Gravity Bridge

**Comment by lightiv** [comment]
Your output show {denom: "dsm"} but my config file above show gravition and ugraviton so I must be missing another config file?? I don't know.   Both config files in /src/configs (testnet | mainnet) both have the same config above. 

![image](https://user-images.githubusercontent.com/36428473/145398588-540bba1b-fc06-45cc-bb21-ae02caaa95d3.png)

**Comment by ryuash** [comment]
No these are the only config files used.
Have you rebuild by any chance?

**Comment by lightiv** [comment]
I will rebuild again.  Thanks

**Comment by lightiv** [comment]
My appologies,  I could sware that I rebuilt it but apparently not.  I just did the rebuild and it is fine.  You can take a look again.
