### ISSUE TITLE
etc: evmos config testing

### ISSUE THREAD

**Issue by ryuash** [forbole/big-dipper-2.0-cosmos#660]
tbd

**Comment by randygrok** [comment]
Is there any example on how to run big dipper on top of evmos somewhere? I cannot make it work. I have all running, bdjuno, hasura but the UI appears empty.

And I got this error:

![image](https://user-images.githubusercontent.com/98407738/151637917-b4916ed1-abab-4e2b-b70b-9c2ea07c2baf.png)

**Comment by ryuash** [comment]
@randygrok exactly as the error says, it's complaining that we're breaking the rules and trying to divide the bonded tokens by 0.

Changing the following `.div(bondedTokens)` to `.div(bondedTokens || 1)` should fix the ui error but this tells me the data did not get saved correctly in psql.

**Comment by ryuash** [comment]
Closing as chain and config has been tested.
