### ISSUE TITLE
Getting errors on account page

### ISSUE THREAD

**Issue by kwunyeung** [forbole/big-dipper-2.0-cosmos#735]
There are errors on account page sometimes. 

![image](https://user-images.githubusercontent.com/932636/155274083-2a882318-3ff6-4aa7-bad9-4350020dd6e3.png)

Looks like getting these errors while waiting Hasura Actions completing the queries.

**Comment by ryuash** [comment]
Someone updated the actions and changed the return types without notifying ui. I'll add a patch to handle this now 😒

<img width="350" alt="image" src="https://user-images.githubusercontent.com/42913823/155442828-eb99f0bf-be8f-4a96-a034-0e74ba2c9305.png">

**Comment by ryuash** [comment]
update: I'm having bdjuno revert this mess

**Comment by ryuash** [comment]
update: Will do a quick patch to handle the `toUpperCase` error though
