### ISSUE TITLE
https://likecoin.bigdipper.live/

### ISSUE THREAD

**Issue by daisymarisfung** [forbole/big-dipper-2.0-cosmos#736]
The whole thing crashes when checking a wallet address with such an error message:

Opps! Looks like something went wrong :(
If you have time please report it to our github at https://github.com/forbole/big-dipper-2.0-cosmos/issues with the url that caused the error.

[Click here to go back home](https://likecoin.bigdipper.live/)

**Comment by ryuash** [comment]
@daisymarisfung Thanks for reporting.
It should be fixed now. Let me know if there's any other problems. If not, I will close this issue in the next 48 hours.
