### ISSUE TITLE
No data from standard cosmos chains

### ISSUE THREAD

**Issue by AlexanderNtk** [forbole/big-dipper-2.0-cosmos#759]
Describe the bug:
We are working on new chain and do not get any data from bigdipper. 
On console I see following error:
field "genesis" not found in type: 'query_root'- Tertasu on error handle ErrorOrCompleted afterExecute h Ii unstable_runwithpriority WI Oi zi D onmessage.

OS: Rest client and the explorer are running on separate instances both running Ubuntu 20.04.3 LTS
COSMOS SDK - 0.44.5
BD - postgres with bdjuno - 1.1.0
Additional context:
I cheeked database - data is there. 
I checked the  client logs nothing.  How to proceed with debugging?

**Comment by ryuash** [comment]
@AlexanderNtk 
`field "genesis" not found in type: 'query_root'-` This seems like a hasura error.

Can you update the following to your gql url and run `npm run graphql:codegen` in the terminal.
https://github.com/forbole/big-dipper-2.0-cosmos/blob/f1c9080171d03c2483de035e95a90e1539df26e1/codegen.yml#L11

If there are errors there's most likely something wrong with your current hasura setup. 
If there are no errors and you don't mind sharing your graphql url I can see if I can debug on my side

**Comment by AlexanderNtk** [comment]
Got bunch of errors.
`
[errors_bigd_1.10.0.txt](https://github.com/forbole/big-dipper-2.0-cosmos/files/8158700/errors_bigd_10.0.0.txt)
`
Try same on latest release v1.10.1
`npm run graphql:codegen` done with success, but still do not work.
On console:
field "genesis" not found in type: 'query_root'
field "validator" not found in type: 'query_root'
Can we collaborate to fix this?
@ryuash where I can drop you privately info ?

**Comment by ryuash** [comment]
@AlexanderNtk 
Can you check the following for me?

In the hasura console, turn off `x-hasura-admin-secret`

<img width="1177" alt="image" src="https://user-images.githubusercontent.com/42913823/156107082-cc6a5b7e-4e10-4811-94cc-6e238fa13e76.png">

and test this query:

```
query ChainId {
  genesis(limit: 1, order_by: {time: desc}) {
    chainId: chain_id
    time
  }
}
```

If you get the following this most likely is a permissions error from hasura and possibly mean the metadata was imported incorrectly https://docs.bigdipper.live/cosmos-based/parser/hasura#importing-the-metadata.

<img width="1308" alt="image" src="https://user-images.githubusercontent.com/42913823/156107657-f8fdb1ba-f5d6-4fb5-ad22-55294d6ffc06.png">


If it's not the following then, feel free to invite me to a private repo, gist with the url

**Comment by AlexanderNtk** [comment]
I want to write was done without errors. :)
I reimport metadata and got:
Error: [big.js] Division by zero
    NextJS 13
[framework-7687e9f5fb6df3737fc2.js:1:83585](http://54.160.63.232:3001/_next/static/chunks/framework-7687e9f5fb6df3737fc2.js)
    NextJS 21

**Comment by ryuash** [comment]
Whoops! please use the latest base! I just fixed this bug a few hours ago https://github.com/forbole/big-dipper-2.0-cosmos/pull/760

**Comment by AlexanderNtk** [comment]
cloned from base, prepared and now works fine. Do not have errors right now. Thanks.
