### ISSUE TITLE
Base: add back proposal details quorum %

### ISSUE THREAD

**Issue by ryuash** [forbole/big-dipper-2.0-cosmos#788]

**Comment by ryuash** [comment]
@yayay927 my initial thought process is to just add the gov quorum param on the side like so

<img width="1655" alt="image" src="https://user-images.githubusercontent.com/42913823/159684078-d490c6c8-1379-4823-9b00-9653d332f987.png">

**Comment by yayay927** [comment]
@ryuash Hmm it doesn't really make sense to me to add it in the corner. And it's (quorum 33%) not even in the same height as title (voted/ total). Maybe we can ask designer to take a really quick look about where is a good place to show quorum information?

**Comment by yayay927** [comment]
How about somewhere here?
<img width="1362" alt="截圖 2022-03-23 下午4 30 46" src="https://user-images.githubusercontent.com/32444273/159749356-aee4b922-ed65-463c-b512-7efcfd203515.png">

**Comment by ryuash** [comment]
Spoke with Design team and they said they want a `?` icon in the top right corner (similar to the original picture) but when you hover over, a small tooltip will show up and say something like `For a proposal to be considered valid, voting must reach at least xx% quorum`

So the icon can be like 
<img width="89" alt="image" src="https://user-images.githubusercontent.com/42913823/159836713-a3b0c4c1-098f-4029-9410-75db7731788c.png">

**Comment by yayay927** [comment]
@ryuash Okay~ I think it's good to hide information first and when users want they can check.
