### ISSUE TITLE
The last balance is not displayed

### ISSUE THREAD

**Issue by AlexanderNtk** [forbole/big-dipper-2.0-cosmos#807]
We deployed BigDipper version 2.0.1. This version shows transactions, but do not display account balance. BDJuno with hasura actions is up and running. There are no errors in console or network tab in developer extension of browser. What should be done to fix it ?

**Comment by ryuash** [comment]
@AlexanderNtk What bdjuno version are you using and can you confirm that the hasura actions are working as expected in the hasura console?

```
query AccountBalances($address: String!) {
  accountBalances: action_account_balance(address: $address) {
    coins
  }
}
```

<img width="1028" alt="image" src="https://user-images.githubusercontent.com/42913823/161062737-4370b908-347c-47bf-8a0e-5e62dcd78a85.png">

<img width="515" alt="image" src="https://user-images.githubusercontent.com/42913823/161062790-971b9570-6912-48a6-88d2-e598640a3c8a.png">

I've defaulted return values in the event that hasura actions do not return properly but you should be able to find the action query and see the return data in the network tab

**Comment by AlexanderNtk** [comment]
We use bdjuno 2.0.2. hasura-actions work incorrectly. It try to connect on `localhost:3000`. Seems this value is hardcoded, cause in my env all values use domain name. Should it be changed ?

**Comment by ryuash** [comment]
@huichiaotsou can you help?

**Comment by huichiaotsou** [comment]
Hi @AlexanderNtk, To configure customized node for hasura actions, you can add flags to the command, for example: 

bdjuno hasura-actions --rpc <your RPC end point> --grpc <your gRPC end point> --secure

You may remove the --secure flag if your end points are not in https. 

Let me know if this helps.

**Comment by AlexanderNtk** [comment]
@huichiaotsou what endpoint for RPC and gRPC should I point (hasura?)? 
Let me share hasura response.
`{
  "errors": [
    {
      "extensions": {
        "internal": {
          "error": {
            "type": "http_exception",
            "message": "Connection failure",
            "request": {
              "secure": false,
              "path": "/account_balance",
              "responseTimeout": "ResponseTimeoutMicro 30000000",
              "queryString": "",
              "method": "POST",
              "requestHeaders": {
                "Content-Type": "application/json",
                "X-B3-ParentSpanId": "80e7f313f753852c",
                "X-B3-TraceId": "15dc4365730c4244",
                "X-B3-SpanId": "0ae79c286d17c468",
                "User-Agent": "hasura-graphql-engine/v2.3.1"
              },
              "host": "localhost",
              "port": 3000
            }
          },
          "response": null,
          "request": {
            "body": {
              "request_query": "query AccountBalances($address: String!) {\n  accountBalances: action_account_balance(address: $address) {\n    coins\n  }\n}",
              "session_variables": {
                "x-hasura-role": "admin"
              },
              "input": {
                "address": "saage17kplgwny9eatcv49n5wjlq343cxlplame6n60v"
              },
              "action": {
                "name": "action_account_balance"
              }
            },
            "transformed_request": null,
            "url": "http://localhost:3000/account_balance",
            "headers": [
              {
                "value": "application/json",
                "name": "Content-Type"
              }
            ]
          }
        },
        "path": "$",
        "code": "unexpected"
      },
      "message": "http exception when calling webhook"
    }
  ]
}`
