### ISSUE TITLE
APR calculation | community tax

### ISSUE THREAD

**Issue by Jackson-DKMG** [forbole/big-dipper-2.0-cosmos#810]
The APR that is displayed on Big Dipper does not seem to take the community tax into account.

Using the following formula for the APR : `(inflation * (1 - community_tax)) / (bonded_tokens / total_supply)`.

If the tax is set to 0, then the returned value matches Big Dipper's for `Desmos mainnet` : 101%

However, if the actual community tax of 0.2 is factored in, the result is about 81%.

**Comment by kwunyeung** [comment]
Wingman Lee commented: [~accountid:5febf49d849d64011102c1bb] isn’t this an UI issue
