### ISSUE TITLE
hi,,i'm having a problem exploring the main bitsong page

### ISSUE THREAD

**Issue by ahmadfauzanpwt2020** [forbole/big-dipper-2.0-cosmos#830]
https://explorebitsong.com/

**Comment by ryuash** [comment]
Can you clarify what the problem is? There's no issues on my side.

@yayay927 assigning you to follow up

**Comment by ahmadfauzanpwt2020** [comment]
Awesome, thanks!

Pada tanggal Sel, 10 Mei 2022 01.52, Ryuash ***@***.***>
menulis:
