### ISSUE TITLE
Viewing a genesis proposal crashes the UI

### ISSUE THREAD

**Issue by makeworld-the-better-one** [forbole/big-dipper-2.0-cosmos#960]
Using the latest release, `base-v2.1.0`. I've deployed Big Dipper on the Theta testnet. First off, proposals do show up:

![image](https://user-images.githubusercontent.com/25111343/183981631-0d0c7322-d39b-448c-bb06-8ea0921d2ed4.png)

But trying to click one these proposals shows the text for a fraction of a second, then the page reloads and shows an error:

![image](https://user-images.githubusercontent.com/25111343/183981796-0140d2c1-a724-46fe-b960-5cf43a2777d1.png)

Here is the console error:

![image](https://user-images.githubusercontent.com/25111343/183982048-f10ff47c-23dd-4c05-ae52-e9b9623eee49.png)

**Comment by makeworld-the-better-one** [comment]
This appears to only happen with old proposals from the genesis file. Proposals that occurred after bdjuno started running, from recent blocks, display fine in the UI.

**Comment by teamchong** [comment]
sorry for the late reply, is the issue resolved?

**Comment by makeworld-the-better-one** [comment]
I am not sure, I am no longer working on this project.

**Comment by teamchong** [comment]
Thank you for reporting this issue. I appreciate your engagement and the effort you have put into addressing this matter. I will be closing this issue now. Thank you for your contribution and support to the project.
