### ISSUE TITLE
Validator names/monikers are not showing up for most validators

### ISSUE THREAD

**Issue by makeworld-the-better-one** [forbole/big-dipper-2.0-cosmos#961]
Using `base-v2.1.0`.

How are validator names extracted? Right now they are not really showing up. Using Theta testnet.

Some validators show up with names, but only one or two:

![image](https://user-images.githubusercontent.com/25111343/183983456-4380bdf3-9eca-44c2-a2f4-c59083edc923.png)

While in reality most if not all should have names ([source](https://explorer.theta-testnet.polypore.xyz/validators)):

![image](https://user-images.githubusercontent.com/25111343/183983649-cd2f3f4e-0af2-4dc9-adb5-ca22fd081c2d.png)

Here's a specific example with the Theta validator `cosmosvaloper1mngvkkhm6g7nqxh4hcv8hjxvgax4m8xujzt964`. On the [official block explorer](https://explorer.theta-testnet.polypore.xyz/validator/cosmosvaloper1mngvkkhm6g7nqxh4hcv8hjxvgax4m8xujzt964):

![image](https://user-images.githubusercontent.com/25111343/183983830-af125858-ad92-4f7f-b715-767cae209299.png)

On my Big Dipper setup, no name appears:

![image](https://user-images.githubusercontent.com/25111343/183983891-779c645e-0e81-498b-83e7-fec118f95b66.png)

Thanks!

**Comment by makeworld-the-better-one** [comment]
Let me know if this is actually a bdjuno issue instead or something.

**Comment by teamchong** [comment]
sorry for the late reply, is the issue resolved?

**Comment by makeworld-the-better-one** [comment]
I am not sure, I am no longer working on this project.

**Comment by teamchong** [comment]
Thank you for reporting this issue. I appreciate your engagement and the effort you have put into addressing this matter. I will be closing this issue now. Thank you for your contribution and support to the project.
